In [112]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
import difflib

load dataset

In [79]:
data=pd.read_csv("movies.csv")
data.shape

(4803, 24)

select only required columns for recommendation system

In [80]:
s_data=data[["genres","keywords","spoken_languages","overview","production_companies","production_countries","vote_average","cast","crew","director"]]
s_data.head()

,genres,keywords,spoken_languages,overview,production_companies,production_countries,vote_average,cast,crew,director
0,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",7.2,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",6.9,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,Action Adventure Crime,spy based on novel secret agent sequel mi6,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",6.3,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",7.6,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",6.1,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

check no of null values

In [81]:
s_data.isnull().sum()

genres                   28
keywords                412
spoken_languages          0
overview                  3
production_companies      0
production_countries      0
vote_average              0
cast                     43
crew                      0
director                 30
dtype: int64

fill null values with " " empty string

In [82]:
for columns_rows in s_data:
  if columns_rows=="vote_average":
    s_data[columns_rows]=s_data[columns_rows].fillna(0)
  s_data[columns_rows]=s_data[columns_rows].fillna('')

/tmp/ipykernel_3815/3398392697.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_data[columns_rows]=s_data[columns_rows].fillna('')
/tmp/ipykernel_3815/3398392697.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s_data[columns_rows]=s_data[columns_rows].fillna(0)

In [83]:
s_data.head()

,genres,keywords,spoken_languages,overview,production_companies,production_countries,vote_average,cast,crew,director
0,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",7.2,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",6.9,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,Action Adventure Crime,spy based on novel secret agent sequel mi6,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",6.3,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",7.6,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",6.1,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

combing all the selected features

In [84]:
combined_features=s_data["genres"]+' '+s_data["keywords"]+' '+s_data["spoken_languages"]+' '+s_data["overview"]+' '+s_data["production_companies"]+' '+s_data["production_countries"]+' '+s_data["cast"]+' '+s_data["crew"]+' '+s_data["director"]

In [85]:
combined_features.head()

0    Action Adventure Fantasy Science Fiction cultu...
1    Adventure Fantasy Action ocean drug abuse exot...
2    Action Adventure Crime spy based on novel secr...
3    Action Crime Drama Thriller dc comics crime fi...
4    Action Adventure Science Fiction based on nove...
dtype: object

In [86]:
vec=TfidfVectorizer()

In [87]:
vec_features=vec.fit_transform(combined_features)

In [92]:
similarity=cosine_similarity(vec_features)
print(similarity)

[[1.         0.5757168  0.82522998 ... 0.32652876 0.08938812 0.15844721]
 [0.5757168  1.         0.58237051 ... 0.29610434 0.08231816 0.14519601]
 [0.82522998 0.58237051 1.         ... 0.3415958  0.09994837 0.16197072]
 ...
 [0.32652876 0.29610434 0.3415958  ... 1.         0.07300094 0.10598589]
 [0.08938812 0.08231816 0.09994837 ... 0.07300094 1.         0.04855406]
 [0.15844721 0.14519601 0.16197072 ... 0.10598589 0.04855406 1.        ]]

In [99]:
#get all movie titles so that we can find its index and recommend movies
titles=data["original_title"].tolist()
print(titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'シン・ゴジラ', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', '4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Astérix aux Jeux Olympiques', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', '金陵十三釵', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Évolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur et les Minimoys', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Don Gato: El inicio de la pandilla', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Deux frères', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', '天將雄師', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', "Michael Jackson's This Is It", 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', '西游记之孙悟空三打白骨精', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'Un long dimanche de fiançailles', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'The Adventures of Ford Fairlane

In [100]:
movie_name=input("ENTER MOVIE NAME:")

ENTER MOVIE NAME:iron man

In [104]:
#the difflib is used to get the closest match for the given movie name with respect to the movie titles list.
closest=difflib.get_close_matches(movie_name,titles)
closest=closest[0]  #only top is enough
print(closest)

Iron Man

In [110]:
#get index of the closest movie
index=titles.index(closest)

In [116]:
#store each movie with its index and its similarity score with respect to closest movie
store=[]
for i in range(len(similarity[index])):
  store.append((i,similarity[index][i]))
print(store)

[(0, np.float64(0.46394634570831045)), (1, np.float64(0.3920136071622238)), (2, np.float64(0.48247348306677185)), (3, np.float64(0.4901414814638407)), (4, np.float64(0.47135681976868793)), (5, np.float64(0.45202263431719275)), (6, np.float64(0.4170153811440505)), (7, np.float64(0.50150399764799)), (8, np.float64(0.35899757587486913)), (9, np.float64(0.48897260002554815)), (10, np.float64(0.3567604982680603)), (11, np.float64(0.3138442450521952)), (12, np.float64(0.34872990686182115)), (13, np.float64(0.3720335516699805)), (14, np.float64(0.4374711825892962)), (15, np.float64(0.45700320386265325)), (16, np.float64(0.49503758979636137)), (17, np.float64(0.3942546833046541)), (18, np.float64(0.31204713039959886)), (19, np.float64(0.4741043154885631)), (20, np.float64(0.4819851033469222)), (21, np.float64(0.31517311022850675)), (22, np.float64(0.47746751623059114)), (23, np.float64(0.3895172005984983)), (24, np.float64(0.4013017973918249)), (25, np.float64(0.42393574430118286)), (26, np.float64(0.5081883700888693)), (27, np.float64(0.47344330137017065)), (28, np.float64(0.4914834852926337)), (29, np.float64(0.35675043871610695)), (30, np.float64(0.5029182287006279)), (31, np.float64(0.4992805102517335)), (32, np.float64(0.32755065362350305)), (33, np.float64(0.45529535464921894)), (34, np.float64(0.2877282362977402)), (35, np.float64(0.4426542902027584)), (36, np.float64(0.4558335800143611)), (37, np.float64(0.3743252952704746)), (38, np.float64(0.4905817227609447)), (39, np.float64(0.3751635117806427)), (40, np.float64(0.4050787595210418)), (41, np.float64(0.4121696630035114)), (42, np.float64(0.39029395324707583)), (43, np.float64(0.4405261365131743)), (44, np.float64(0.4699044350616148)), (45, np.float64(0.3800064359899433)), (46, np.float64(0.47479989643590104)), (47, np.float64(0.4688459605440804)), (48, np.float64(0.40217580200424974)), (49, np.float64(0.28002179752184336)), (50, np.float64(0.4062453817590671)), (51, np.float64(0.31789533521839713)), (52, np.float64(0.3800306844861064)), (53, np.float64(0.2869852885897832)), (54, np.float64(0.23669475652278077)), (55, np.float64(0.36648164906483066)), (56, np.float64(0.4746911606746742)), (57, np.float64(0.41985132890016036)), (58, np.float64(0.3284704501676677)), (59, np.float64(0.45651142267465067)), (60, np.float64(0.1943126001855967)), (61, np.float64(0.44337914778115156)), (62, np.float64(0.26786689699637733)), (63, np.float64(0.35922300183565364)), (64, np.float64(0.482151521972305)), (65, np.float64(0.4628936759333956)), (66, np.float64(0.44244899361983503)), (67, np.float64(0.22529622541859004)), (68, np.float64(1.0000000000000004)), (69, np.float64(0.45147088211561287)), (70, np.float64(0.24635444727667377)), (71, np.float64(0.3172556142743977)), (72, np.float64(0.46432699654198006)), (73, np.float64(0.3897074830239229)), (74, np.float64(0.4730626855986374)), (75, np.float64(0.43230007935179704)), (76, np.float64(0.354663471359494)), (77, np.float64(0.38134918435467025)), (78, np.float64(0.40738582996861983)), (79, np.float64(0.5629140112432699)), (80, np.float64(0.4231548867961054)), (81, np.float64(0.2266681490858473)), (82, np.float64(0.4839165247230729)), (83, np.float64(0.4481630838785762)), (84, np.float64(0.43206321653418767)), (85, np.float64(0.44046395025837104)), (86, np.float64(0.15401849812170096)), (87, np.float64(0.4509181950665105)), (88, np.float64(0.40318483778189984)), (89, np.float64(0.35837768063049236)), (90, np.float64(0.48509504977541446)), (91, np.float64(0.47110177425306154)), (92, np.float64(0.39169107687713206)), (93, np.float64(0.5004011353925664)), (94, np.float64(0.4865694457247986)), (95, np.float64(0.4766777994472844)), (96, np.float64(0.3112131980236156)), (97, np.float64(0.2749445193717)), (98, np.float64(0.4320199811829406)), (99, np.float64(0.4846748982887846)), (100, np.float64(0.47647838699136236)), (101, np.float64(0.42062051955939117)), (102, np.float64(0.4786646724774989)), (103, np.float64(0.16468434580365088)), (104, np.float64(0.3841121636179836)), (105, np.float64(0.4570398055057122)), (106, np.float64(0.28489272898241863)), (107, np.float64(0.4822512169026364)), (108, np.float64(0.4732999002803561)), (109, np.float64(0.38265662912173565)), (110, np.float64(0.47919338038379955)), (111, np.float64(0.4235410352228054)), (112, np.float64(0.49948884074290156)), (113, np.float64(0.3350839609021644)), (114, np.float64(0.3746172901286345)), (115, np.float64(0.3687621453488265)), (116, np.float64(0.33233442195211205)), (117, np.float64(0.47824140221125594)), (118, np.float64(0.3968597833767919)), (119, np.float64(0.49621411508650154)), (120, np.float64(0.15936379382583496)), (121, np.float64(0.28188031192661356)), (122, np.float64(0.2819290322798486)), (123, np.float64(0.3417710462346423)), (124, np.float64(0.32714521899835014)), (125, np.float64(0.2699785702138116)), (126, np.float64(0.44079990958247645)), (127, np.float64(0.45089642240647704)), (128, np.float64(0.4794421055607358)), (129, np.float64(0.42489838705041594)), (130, np.float64(0.39822026954811457)), (131, np.float64(0.27404616916325986)), (132, np.float64(0.36113707166281067)), (133, np.float64(0.31797806980860616)), (134, np.float64(0.47119907061715405)), (135, np.float64(0.4208134165229452)), (136, np.float64(0.3019435748836434)), (137, np.float64(0.2867526739747804)), (138, np.float64(0.14479994401266066)), (139, np.float64(0.36396123337302216)), (140, np.float64(0.3099097372092309)), (141, np.float64(0.1851181665366446)), (142, np.float64(0.3480256587539286)), (143, np.float64(0.3363009899490823)), (144, np.float64(0.2646504520144951)), (145, np.float64(0.4762736224313517)), (146, np.float64(0.2215829359719912)), (147, np.float64(0.2068798694853425)), (148, np.float64(0.47943591265613333)), (149, np.float64(0.47380380771654884)), (150, np.float64(0.4866228845984046)), (151, np.float64(0.4397923309037007)), (152, np.float64(0.35325959532025614)), (153, np.float64(0.3776049081635175)), (154, np.float64(0.23951536919689878)), (155, np.float64(0.39248347667228284)), (156, np.float64(0.31793400034037467)), (157, np.float64(0.47726337188938645)), (158, np.float64(0.3429046303200779)), (159, np.float64(0.5052440362726399)), (160, np.float64(0.3374676307059421)), (161, np.float64(0.4387288790105201)), (162, np.float64(0.37693156029078045)), (163, np.float64(0.35095216656984385)), (164, np.float64(0.46750705233651446)), (165, np.float64(0.5097000953367585)), (166, np.float64(0.3723902711355648)), (167, np.float64(0.49328352765743066)), (168, np.float64(0.3850945772155827)), (169, np.float64(0.49270350398117835)), (170, np.float64(0.35922034463032837)), (171, np.float64(0.49236376445236923)), (172, np.float64(0.4639991177138704)), (173, np.float64(0.31538278840108397)), (174, np.float64(0.41634016987201644)), (175, np.float64(0.2847366872417844)), (176, np.float64(0.47132954505739116)), (177, np.float64(0.24220369385424115)), (178, np.float64(0.24368737938533658)), (179, np.float64(0.13887394342863157)), (180, np.float64(0.4955373063570423)), (181, np.float64(0.24129359127487912)), (182, np.float64(0.5139723372712899)), (183, np.float64(0.4147225574583171)), (184, np.float64(0.35302360856161075)), (185, np.float64(0.4903908727085726)), (186, np.float64(0.49550385217493265)), (187, np.float64(0.3182701547714195)), (188, np.float64(0.2527356090398678)), (189, np.float64(0.4484783507346775)), (190, np.float64(0.3906869928769292)), (191, np.float64(0.487785535359351)), (192, np.float64(0.43537408703790337)), (193, np.float64(0.4312823012236159)), (194, np.float64(0.3074599690662931)), (195, np.float64(0.4550148287332799)), (196, np.float64(0.29616920704040106)), (197, np.float64(0.4846658760671431)), (198, np.float64(0.3887957158252899)), (199, np.float64(0.48090929612616573)), (200, np.float64(0.47167798933921395)), (201, np.float64(0.4722299638200844)), (202, np.float64(0.3127653021441981)), (203, np.float64(0.38327651362794946)), (204, np.float64(0.4732755002200155)), (205, np.float64(0.40171553616312283)), (206, np.float64(0.48006389079840933)), (207, np.float64(0.34821368205143083)), (208, np.float64(0.29921829239908376)), (209, np.float64(0.4635962669208105)), (210, np.float64(0.4707066474191185)), (211, np.float64(0.2775027342294304)), (212, np.float64(0.4975089492225142)), (213, np.float64(0.4841027492763421)), (214, np.float64(0.27366831783503326)), (215, np.float64(0.46847703149268194)), (216, np.float64(0.35306254171379037)), (217, np.float64(0.43014259226328166)), (218, np.float64(0.47457959158487883)), (219, np.float64(0.281249027697008)), (220, np.float64(0.4621957634790724)), (221, np.float64(0.22540333427524936)), (222, np.float64(0.46433670523627285)), (223, np.float64(0.49423006548031445)), (224, np.float64(0.33443783867832155)), (225, np.float64(0.3303524325549714)), (226, np.float64(0.3215891648883988)), (227, np.float64(0.47967555604172224)), (228, np.float64(0.3555737311962248)), (229, np.float64(0.24241394820503348)), (230, np.float64(0.2816761677589632)), (231, np.float64(0.4538742092792557)), (232, np.float64(0.4854239869623886)), (233, np.float64(0.2937359257433508)), (234, np.float64(0.259742459959969)), (235, np.float64(0.2992359790009283)), (236, np.float64(0.37698843333438964)), (237, np.float64(0.19693230387231977)), (238, np.float64(0.36234565621279446)), (239, np.float64(0.40607421813671596)), (240, np.float64(0.46932672742339926)), (241, np.float64(0.27359663821848085)), (242, np.float64(0.49239049593863055)), (243, np.float64(0.3047967133863383)), (244, np.float64(0.45932758014464353)), (245, np.float64(0.33074876505121453)), (246, np.float64(0.48279230458828243)), (247, np.float64(0.47753805940640953)), (248, np.float64(0.3172512510269505)), (249, np.float64(0.4594033047903124)), (250, np.float64(0.4947396628878613)), (251, np.float64(0.35078881879550944)), (252, np.float64(0.2748568204096165)), (253, np.float64(0.44819957723921955)), (254, np.float64(0.34901158239342445)), (255, np.float64(0.3782703178045507)), (256, np.float64(0.44527652239150606)), (257, np.float64(0.4256892583181867)), (258, np.float64(0.18532729438448353)), (259, np.float64(0.47629960574432606)), (260, np.float64(0.46801547215353495)), (261, np.float64(0.47465824796337003)), (262, np.float64(0.37462358196568535)), (263, np.float64(0.48941784728978016)), (264, np.float64(0.3732672355599685)), (265, np.float64(0.29429153884308396)), (266, np.float64(0.48850121236748584)), (267, np.float64(0.4886310670245706)), (268, np.float64(0.22829447325032884)), (269, np.float64(0.4169852015407383)), (270, np.float64(0.4569387221647988)), (271, np.float64(0.4224294845286105)), (272, np.float64(0.09220913975812206)), (273, np.float64(0.3726993515572002)), (274, np.float64(0.45817839250708065)), (275, np.float64(0.4922866726512035)), (276, np.float64(0.48715579575664475)), (277, np.float64(0.4820907216150911)), (278, np.float64(0.32365665513897995)), (279, np.float64(0.4473535245409027)), (280, np.float64(0.4703374711424812)), (281, np.float64(0.443375984179188)), (282, np.float64(0.3916999830879312)), (283, np.float64(0.3249084949342164)), (284, np.float64(0.2222553331147032)), (285, np.float64(0.18165390464761322)), (286, np.float64(0.4510850739370279)), (287, np.float64(0.4607916125342303)), (288, np.float64(0.37645359847733506)), (289, np.float64(0.3175672567345189)), (290, np.float64(0.4686435229237357)), (291, np.float64(0.48479511580916085)), (292, np.float64(0.36987083120182473)), (293, np.float64(0.21168539877760714)), (294, np.float64(0.3438554020986271)), (295, np.float64(0.3653713269891932)), (296, np.float64(0.48405291107619414)), (297, np.float64(0.4651367862577574)), (298, np.float64(0.48612190030821706)), (299, np.float64(0.2999334009135329)), (300, np.float64(0.40772582524325424)), (301, np.float64(0.4691431824578371)), (302, np.float64(0.2599549814542739)), (303, np.float64(0.4992595087515481)), (304, np.float64(0.43625183983440596)), (305, np.float64(0.37762725852348417)), (306, np.float64(0.33228686386008627)), (307, np.float64(0.44870709187861113)), (308, np.float64(0.462936705942998)), (309, np.float64(0.26241594851142913)), (310, np.float64(0.4527087420721701)), (311, np.float64(0.22191507819889367)), (312, np.float64(0.46773114601116755)), (313, np.float64(0.2634895919670571)), (314, np.float64(0.32974672253766396)), (315, np.float64(0.26053127590392106)), (316, np.float64(0.39391714258802785)), (317, np.float64(0.37051203949505374)), (318, np.float64(0.2835843323463027)), (319, np.float64(0.3336023482716468)), (320, np.float64(0.48772376520926297)), (321, np.float64(0.2516597400457633)), (322, np.float64(0.4803798388430857)), (323, np.float64(0.3181434493835129)), (324, np.float64(0.36594482275559576)), (325, np.float64(0.25531396885081825)), (326, np.float64(0.43182631000832616)), (327, np.float64(0.36466743377287875)), (328, np.float64(0.44566838478132664)), (329, np.float64(0.37703218386380344)), (330, np.float64(0.39550573454059396)), (331, np.float64(0.4254669048825759)), (332, np.float64(0.42466747075208533)), (333, np.float64(0.4392002221612379)), (334, np.float64(0.47866738439620193)), (335, np.float64(0.46827499881873125)), (336, np.float64(0.4670997962125908)), (337, np.float64(0.46150839646436703)), (338, np.float64(0.49023265208986416)), (339, np.float64(0.45031585867628937)), (340, np.float64(0.28344735381467057)), (341, np.float64(0.42074638177920876)), (342, np.float64(0.47630552274760224)), (343, np.float64(0.42804813706771067)), (344, np.float64(0.3680316983070142)), (345, np.float64(0.22111911875410115)), (346, np.float64(0.47564115421701864)), (347, np.float64(0.3156361044605037)), (348, np.float64(0.20140501638747205)), (349, np.float64(0.3443974251212644)), (350, np.float64(0.39483261467544944)), (351, np.float64(0.45307174545957324)), (352, np.float64(0.34122805590377286)), (353, np.float64(0.3670875448495736)), (354, np.float64(0.4779113253723445)), (355, np.float64(0.4135732346634514)), (356, np.float64(0.3740156351307737)), (357, np.float64(0.226070944278567)), (358, np.float64(0.43698091285955126)), (359, np.float64(0.26369511279765867)), (360, np.float64(0.34349109581040455)), (361, np.float64(0.40171442385433614)), (362, np.float64(0.38756902927524606)), (363, np.float64(0.4849256054926825)), (364, np.float64(0.23672520679034115)), (365, np.float64(0.49176002615844433)), (366, np.float64(0.26727057240607316)), (367, np.float64(0.4851234393274679)), (368, np.float64(0.3707265945771608)), (369, np.float64(0.2679843039624841)), (370, np.float64(0.4372527801843228)), (371, np.float64(0.2990877007156283)), (372, np.float64(0.4071164667603334)), (373, np.float64(0.40092243164609176)), (374, np.float64(0.24772688716975502)), (375, np.float64(0.23008486122842822)), (376, np.float64(0.2143122184580614)), (377, np.float64(0.2872337222100628)), (378, np.float64(0.28879517890526724)), (379, np.float64(0.42114693500286965)), (380, np.float64(0.4314380452485078)), (381, np.float64(0.12276687199914108)), (382, np.float64(0.4443197809687279)), (383, np.float64(0.46667075054885865)), (384, np.float64(0.2764055730333166)), (385, np.float64(0.42431555273431887)), (386, np.float64(0.49027412186492336)), (387, np.float64(0.471953261060459)), (388, np.float64(0.4810341509161682)), (389, np.float64(0.3693765270462341)), (390, np.float64(0.25071964442961303)), (391, np.float64(0.322048232553259)), (392, np.float64(0.34943414753229923)), (393, np.float64(0.2349312102524044)), (394, np.float64(0.3298479943270701)), (395, np.float64(0.23662961832642168)), (396, np.float64(0.3310318660678858)), (397, np.float64(0.26592971616898115)), (398, np.float64(0.4152852298835236)), (399, np.float64(0.2523405405162006)), (400, np.float64(0.4637114282939061)), (401, np.float64(0.44968921294855646)), (402, np.float64(0.38418815833141884)), (403, np.float64(0.46861996415100227)), (404, np.float64(0.3004408188465605)), (405, np.float64(0.44375807445275606)), (406, np.float64(0.35214805651682285)), (407, np.float64(0.4495210712011467)), (408, np.float64(0.4903271837168576)), (409, np.float64(0.24603776890119394)), (410, np.float64(0.39674230339079847)), (411, np.float64(0.17866799310915898)), (412, np.float64(0.497988213927985)), (413, np.float64(0.2766496971855596)), (414, np.float64(0.48435638346316473)), (415, np.float64(0.449739260182939)), (416, np.float64(0.2952405276567107)), (417, np.float64(0.28624917956780593)), (418, np.float64(0.24684732051026648)), (419, np.float64(0.4682137094086039)), (420, np.float64(0.2732339329021887)), (421, np.float64(0.40766503661220604)), (422, np.float64(0.435873045528514)), (423, np.float64(0.47626409169163125)), (424, np.float64(0.4749440744057978)), (425, np.float64(0.4691852324199636)), (426, np.float64(0.42586963128862604)), (427, np.float64(0.1436690680518773)), (428, np.float64(0.2646827567621806)), (429, np.float64(0.25987047763671817)), (430, np.float64(0.34662565349332086)), (431, np.float64(0.35551548559090945)), (432, np.float64(0.4739334277635056)), (433, np.float64(0.2940498457493108)), (434, np.float64(0.31616910639722956)), (435, np.float64(0.25042959087114985)), (436, np.float64(0.29710586450515825)), (437, np.float64(0.287179510559279)), (438, np.float64(0.18331987585739565)), (439, np.float64(0.37186242424014415)), (440, np.float64(0.3233460724730445)), (441, np.float64(0.42508603327261113)), (442, np.float64(0.41587140073105805)), (443, np.float64(0.13447639464891425)), (444, np.float64(0.4727484849587685)), (445, np.float64(0.41958884135136487)), (446, np.float64(0.3945927494343733)), (447, np.float64(0.4750159002263752)), (448, np.float64(0.4501413750413405)), (449, np.float64(0.46507644260029435)), (450, np.float64(0.24098189194329916)), (451, np.float64(0.4755192032878294)), (452, np.float64(0.47402598812269475)), (453, np.float64(0.34734917937686693)), (454, np.float64(0.44465618171921667)), (455, np.float64(0.3037788377202471)), (456, np.float64(0.46302338737332455)), (457, np.float64(0.37722709277718197)), (458, np.float64(0.17303374418430775)), (459, np.float64(0.3251836103363987)), (460, np.float64(0.20713408554492924)), (461, np.float64(0.4758741400931571)), (462, np.float64(0.4639493536119964)), (463, np.float64(0.11529316042975969)), (464, np.float64(0.20607911439569898)), (465, np.float64(0.3883324499757676)), (466, np.float64(0.3343047302051738)), (467, np.float64(0.3048601129734503)), (468, np.float64(0.24134010633618197)), (469, np.float64(0.3237221858856689)), (470, np.float64(0.2826730665079562)), (471, np.float64(0.21610021540328483)), (472, np.float64(0.4735308850538609)), (473, np.float64(0.3377549635791749)), (474, np.float64(0.27659186455176926)), (475, np.float64(0.18382946478315162)), (476, np.float64(0.37503485806583114)), (477, np.float64(0.3856673259665868)), (478, np.float64(0.4564447386908897)), (479, np.float64(0.23026308620310504)), (480, np.float64(0.25436158522569896)), (481, np.float64(0.4263759475397942)), (482, np.float64(0.15195656174739752)), (483, np.float64(0.4808324718014964)), (484, np.float64(0.26746384943826496)), (485, np.float64(0.2462466085255663)), (486, np.float64(0.4430611623132482)), (487, np.float64(0.46656971276531617)), (488, np.float64(0.3100771448968675)), (489, np.float64(0.3112349546345334)), (490, np.float64(0.3807040379855626)), (491, np.float64(0.4058543356671541)), (492, np.float64(0.11951139405108115)), (493, np.float64(0.43234479270736664)), (494, np.float64(0.36461526471876915)), (495, np.float64(0.4450810927607783)), (496, np.float64(0.34812065766127037)), (497, np.float64(0.2235013657792237)), (498, np.float64(0.4757892083687859)), (499, np.float64(0.2634172950682122)), (500, np.float64(0.4756775833090413)), (501, np.float64(0.18466956731538722)), (502, np.float64(0.33317365255591724)), (503, np.float64(0.22079740994744004)), (504, np.float64(0.3919637485417319)), (505, np.float64(0.493830665794055)), (506, np.float64(0.35640396824254916)), (507, np.float64(0.4302231356795349)), (508, np.float64(0.46242401132741195)), (509, np.float64(0.

In [119]:
#sort the list in descending order with respect to similarity score
store=sorted(store,key=lambda x:x[1], reverse=True)

In [128]:
#print only top 20 movie match
for i in range(len(store)):
  if i>19:
    break
  index=store[i][0]
  print(i+1,titles[index])

1 Iron Man
2 Iron Man 2
3 Ant-Man
4 Hulk
5 Captain America: Civil War
6 Blade: Trinity
7 Spider-Man
8 Spider-Man 2
9 Avengers: Age of Ultron
10 Terminator 3: Rise of the Machines
11 Alexander
12 Iron Man 3
13 Catwoman
14 Elektra
15 The Core
16 Blade II
17 The Day After Tomorrow
18 The Punisher
19 Batman Begins
20 The Bourne Ultimatum

Full work

In [129]:
#use all the parts into one for easy understand
movie_name=input("ENTER MOVIE NAME:")
closest=difflib.get_close_matches(movie_name,titles)
closest=closest[0]  #only top is enough
index=titles.index(closest)
store=[]
for i in range(len(similarity[index])):
  store.append((i,similarity[index][i]))
store=sorted(store,key=lambda x:x[1], reverse=True)
for i in range(len(store)):
  if i>19:
    break
  index=store[i][0]
  print(i+1,titles[index])

ENTER MOVIE NAME:king kong
1 King Kong
2 The Hobbit: The Desolation of Smaug
3 The Hobbit: The Battle of the Five Armies
4 War of the Worlds
5 The Chronicles of Riddick
6 Alexander
7 The Day After Tomorrow
8 The Core
9 Jurassic World
10 Master and Commander: The Far Side of the World
11 The Dark Knight Rises
12 Ant-Man
13 Catwoman
14 Kill Bill: Vol. 1
15 Harry Potter and the Chamber of Secrets
16 Contact
17 Minority Report
18 Harry Potter and the Prisoner of Azkaban
19 A.I. Artificial Intelligence
20 Harry Potter and the Philosopher's Stone